name: bip_card_info
description: Bip Card Info Mobile App.

version: 0.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  html: ^0.14.0+3

  flutter_bloc: ^2.1.1
  equatable: ^1.0.1
  flutter_spinkit: "^4.1.0"
  flutter_staggered_animations: "^0.1.2"

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
